### ISSUE TITLE
'utf-8' codec can't decode byte 0x98 in position 0

### ISSUE THREAD

**Issue by williamwmd** [jaidenlabelle/tuya-vacuum-maps#3]
I am using version v0.1.4, and when I try to configure the integration I am getting an error "Unknown error occurred."
I have tried several times but the error persists, if I try to configure using the same credentials in the other integration (https://github.com/oven-lab/tuya_cloud_map_extractor), the configuration is successful.

![image](https://github.com/user-attachments/assets/0b6f4930-0400-4f74-99e6-294928ac1943)

This is the request:

POST - http://homeassistant.local:8123/api/config/config_entries/flow/01JDPNTN1RQP6R7MS28WNF0XEB
`{"name":"Vacuum Map","server":"https://openapi.tuyaus.com","client_id":"123...","client_secret":"123...","device_id":"123..."}`
I changed my real credentials to "123..."

RESPONSE:
```
{
    "type": "form",
    "flow_id": "01JDPNTN1RQP6R7MS28WNF0XEB",
    "handler": "tuya_vacuum_maps",
    "data_schema": [
        {
            "type": "string",
            "name": "name",
            "required": true,
            "default": "Vacuum Map"
        },
        {
            "type": "select",
            "options": [
                [
                    "https://openapi.tuyacn.com",
                    "China"
                ],
                [
                    "https://openapi.tuyaus.com",
                    "Western America"
                ],
                [
                    "https://openapi-ueaz.tuyaus.com",
                    "Eastern America"
                ],
                [
                    "https://openapi.tuyaeu.com",
                    "Central Europe"
                ],
                [
                    "https://openapi-weaz.tuyaeu.com",
                    "Western Europe"
                ],
                [
                    "https://openapi.tuyain.com",
                    "India"
                ]
            ],
            "name": "server",
            "required": true,
            "default": "https://openapi.tuyaus.com"
        },
        {
            "type": "string",
            "name": "client_id",
            "required": true,
            "default": ""
        },
        {
            "type": "string",
            "name": "client_secret",
            "required": true,
            "default": ""
        },
        {
            "type": "string",
            "name": "device_id",
            "required": true,
            "default": ""
        }
    ],
    "errors": {
        "base": "Unknown error occurred."
    },
    "description_placeholders": null,
    "last_step": null,
    "preview": null,
    "step_id": "user"
}
```

**Comment by williamwmd** [comment]
> Check HASS logs for more details. There will be more info. For me, it was a wrong server. Central Europe worked for me.


I'm using the correct locale, anyway I've tested all the other locales and the same error occurs in all of them.

![image](https://github.com/user-attachments/assets/2748c767-709f-4024-9e35-355c7c494d68)

Logs:
![image](https://github.com/user-attachments/assets/20d922ce-652d-4d98-96d6-db007894d00e)

`Registrador: homeassistant.util.loop
Fonte: util/loop.py:136
Ocorreu pela primeira vez: 15:01:47 (1 ocorrências)
Último registro: 15:01:47

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f6514aed0>,) inside the event loop by custom integration 'tuya_vacuum_maps' at custom_components/tuya_vacuum_maps/config_flow.py, line 31: vacuum = tuya_vacuum.TuyaVacuum( (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/jaidenlabelle/tuya-vacuum-maps/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 556, in start task = asyncio.Task(coro, loop=loop, eager_start=True) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/tuya_vacuum_maps/config_flow.py", line 61, in async_step_user await validate_input(user_input) File "/config/custom_components/tuya_vacuum_maps/config_flow.py", line 31, in validate_input vacuum = tuya_vacuum.TuyaVacuum(`

`Este erro originou-se de uma integração personalizada.

Registrador: tuya_vacuum.vacuum
Fonte: custom_components/tuya_vacuum_maps/config_flow.py:35
integração: Tuya Vacuum Maps (documentação, problemas)
Ocorreu pela primeira vez: 15:01:50 (1 ocorrências)
Último registro: 15:01:50

Unknown map type: 3`

` Este erro originou-se de uma integração personalizada.

Registrador: custom_components.tuya_vacuum_maps.config_flow
Fonte: custom_components/tuya_vacuum_maps/config_flow.py:68
integração: Tuya Vacuum Maps (documentação, problemas)
Ocorreu pela primeira vez: 15:01:50 (1 ocorrências)
Último registro: 15:01:50

Error occurred while validating: 'utf-8' codec can't decode byte 0x98 in position 0: invalid start byte `

**Comment by jaidenlabelle** [comment]
This looks like a map parsing issue and not a configuration issue. I'm working on adding diagnostics #5 so that I can fix this issue.
